Import('env')
Import('src_env')

env.ProtocolBuffer(['fast_leader_election.proto',
  'server_config.proto'])

proto_src_files = [
  'fast_leader_election.pb.cc',
  'server_config.pb.cc',
]

proto_env = src_env.Clone()
proto_env['srcroot'] += '/proto'
proto_env['objroot'] += '/proto'
proto_obj_files = []
for file in proto_src_files:
  proto_obj_files += proto_env.Object(file)

proto_env.StaticLibrary('global_proto', proto_obj_files)
