Import('env')
Import('src_env')

common_src_files = [
  'fast_leader_electioner.cpp',
]

common_env = src_env.Clone()
common_env['srcroot'] += '/common'
common_env['objroot'] += '/common'
common_obj_files = []
for file in common_src_files:
  common_obj_files += common_env.Object(file)

common_env.StaticLibrary('global_common', common_obj_files)
