Import('env')

src_env = env.Clone()
src_env['extension'] = 'cpp'
src_env['srcroot'] += '/src'
src_env['objroot'] += '/src'

src_env.Append(CPPPATH=[src_env['srcroot']])

subdirs=[
 'proto',
 'server',
]


Export('src_env')

src_files = []
for x in subdirs:
  target_dir='%s/%s/' % (src_env['objroot'], x)
  SConscript('%s/%s/SConscript' % (src_env['srcroot'], x), build_dir=target_dir,
  duplicate=0)
