import os
import platform

env = DefaultEnvironment()
dbg = ARGUMENTS.get('dbg', 0)
opt = ARGUMENTS.get('opt', 0)

if int(opt) == 1:
  env.Append(CCFLAGS=' -g -O2 ')
  env['objroot'] = env.Dir('build/opt').abspath
  env['DEBUG'] = False
else:
  env.Append(CCFLAGS=' -g ')
  env['objroot'] = env.Dir('build/dbg').abspath
  env['DEBUG'] = True

env['srcroot'] = env.Dir('.').abspath
objroot = env['objroot']
srcroot = env['srcroot']
Export('env')

subdir = ['src', ]

for x in subdir:
  target_dir = '%s/%s' % (env['objroot'], x)
  SConscript('%s/%s/SConscript' % (env['srcroot'], x), build_dir=target_dir,
  duplicate=0)

