Import('env')
Import('src_env')

server_src_files = [
  'main.cpp',
  'fast_leader_electioner.cpp',
]

server_env = src_env.Clone()
server_env['srcroot'] += '/server'
server_env['objroot'] += '/server'
server_env.Append(LIBPATH=[
  src_env['objroot'] + '/proto',
])

server_env.Append(CPPPATH=[
  src_env['objroot'],
])

server_env.Prepend(LIBS=[
  'pthread',
  'event',
  'eventrpc',
  'global_proto',
])

server_obj_files = []
for file in server_src_files:
  server_obj_files += server_env.Object(file)

server_env.Program('global_server', server_obj_files)
