Import('env')

src_env = env.Clone()
src_env['extension'] = 'cpp'
src_env['srcroot'] += '/eventrpc'
src_env['objroot'] += '/eventrpc'

src_env.Append(CPPPATH=[src_env['srcroot']])
Export('src_env')

src_files = []
src_files = Glob('./*.' + src_env['extension'])

src_env.StaticLibrary('eventrpc', src_files)
