Import('env')

src_env = env.Clone()
src_env['extension'] = 'cpp'
src_env['srcroot'] += '/eventrpc'
src_env['objroot'] += '/eventrpc'

src_env.Append(CPPPATH=[src_env['srcroot'], ])
Export('src_env')

src_files = [
  'atomic.cpp',
  'ref_count.cpp',
  'log.cpp',
  'thread.cpp',
  'utility.cpp',
  'time_utility.cpp',
  'monitor.cpp',
  'lookup3.cpp',
]

src_env.StaticLibrary('eventrpc', src_files)
