Import('env')

sample_env = env.Clone()
sample_env['objroot'] += '/sample'
sample_env['srcroot'] += '/eventrpc'
sample_env['extension'] = 'cpp'
sample_env.Append(CPPPATH=[sample_env['srcroot'],
  env['objroot'] + '/sample'])
sample_env.Append(LIBPATH=[env['objroot']+'/eventrpc',])
sample_env.Prepend(LIBS=
  [
    'eventrpc',
  ])

env.ProtocolBuffer('echo.proto')

sample_env.Program('echo_message_client', ['echo_message_client.cpp', 'echo.pb.cc'])
sample_env.Program('echo_message_server', ['echo_message_server.cpp', 'echo.pb.cc'])
#sample_env.Program('echo_client', ['echo_client.cpp', 'echo.pb.cc'])
#sample_env.Program('echo_server', ['echo_server.cpp', 'echo.pb.cc'])

