Import('env')

unittest_env = env.Clone()
unittest_env['objroot'] += '/unittest'
unittest_env['srcroot'] += '/unittest'
Export('unittest_env')

subdir=['cpp',]

for x in subdir:
  target_dir='%s/%s' % (unittest_env['objroot'], x)
  SConscript('%s/%s/SConscript' % (unittest_env['srcroot'], x), build_dir=target_dir, duplicate=0)
