Import('env')

unittest_env = env.Clone()
unittest_env['objroot'] += '/unittest'
unittest_env['srcroot'] += '/src'
unittest_env['extension'] = 'cpp'
unittest_env.Append(CPPPATH=[unittest_env['srcroot']])
unittest_env.Append(LIBPATH=[env['objroot']+'/src',])
unittest_env.Prepend(LIBS=
  [
    'eventrpc',
    'pthread',
    'event',
    'protobuf',
  ])

Export('unittest_env')

subdirs=[
 'base',
 'concurrency',
 'net',
 'smart_ptr',
 'util',
 'log',
]

unittest_env['CCFLAGS'] = env['CCFLAGS']
src_files = []
for x in subdirs:
  target_dir='%s/%s/' % (unittest_env['objroot'], x)
  src_files += Glob(target_dir + '*.' + unittest_env['extension'])

for file in src_files:
  unittest_env.Program(file)
