Import('unittest_env')
Import('src_cpp_env')

unittest_cpp_env = unittest_env.Clone()
unittest_cpp_env['objroot'] += '/cpp'
unittest_cpp_env['srcroot'] += '/cpp'
unittest_cpp_env['extension'] = 'cpp'
unittest_cpp_env.Append(CPPPATH=[src_cpp_env['srcroot']])
unittest_cpp_env.Append(LIBPATH=[src_cpp_env['objroot']])
unittest_cpp_env.Prepend(LIBS=
  [
    'eventrpc',
    'pthread',
    'event',
    'protobuf',
  ])

Export('unittest_cpp_env')

subdirs=[
 'base',
 'concurrency',
 'net',
 'smart_ptr',
 'util',
 'log',
]

src_files = []
for x in subdirs:
  target_dir='%s/%s/' % (unittest_cpp_env['objroot'], x)
  src_files += Glob(target_dir + '*.' + unittest_cpp_env['extension'])

for file in src_files:
  unittest_cpp_env.Program(file)
