Import('unittest_env')

unittest_cpp_env = unittest_env.Clone()
unittest_cpp_env['objroot'] += '/cpp'
unittest_cpp_env['srcroot'] += '/cpp'
unittest_cpp_env['extension'] = 'cpp'
unittest_cpp_env.Append(CPPPATH=[unittest_cpp_env['srcroot']])
Export('unittest_cpp_env')

subdirs=[
 'base',
 'concurrency',
 'net',
 'smart_ptr',
 'util',
]

src_files = []
for x in subdirs:
  target_dir='%s/%s/' % (unittest_cpp_env['objroot'], x)
  src_files += Glob(target_dir + '*.' + unittest_cpp_env['extension'])

unittest_cpp_env.StaticLibrary('eventrpc', src_files)
unittest_cpp_env.SharedLibrary('eventrpc', src_files)
