Import('env')

src_env = env.Clone()
src_env['objroot'] += '/src'
src_env['srcroot'] += '/src'
Export('src_env')

subdir=['cpp',]

for x in subdir:
  target_dir='%s/%s' % (src_env['objroot'], x)
  SConscript('%s/%s/SConscript' % (src_env['srcroot'], x), build_dir=target_dir, duplicate=0)
