Import('env')

global_env = env.Clone()
global_env['extension'] = 'cpp'
global_env['srcroot'] += '/global'
global_env['objroot'] += '/global'

Export('global_env')

src_files = [
  #'quorum_peer_main.cpp',
  #'quorum_peer_server.cpp',
  #'quorum_peer_manager.cpp',
  #'fast_leader_election.cpp',
  'transaction_log.cpp',
  'utility.cpp',
]

protobuf_files = [
  '../protocol/server_config.pb.cc',
  '../protocol/leader_election.pb.cc',
]

global_env.ProtocolBuffer('transaction.proto')
global_env.ProtocolBuffer('record.proto')
global_env.StaticLibrary('global', src_files)
